import { library } from '@fortawesome/fontawesome-svg-core'

// Regular
import {
  faAnalytics,
  faBars,
  faBrain,
  faEnvelope as faEnvelopeReg,
  faTimes,
  faPercent,
  faNewspaper,
  faLockAlt,
  faInfoSquare,
  faInfoCircle as faInfoCircleReg,
  faQuestionCircle as faQuestionCircleReg,
  faDollarSign,
  faTags as faTagsReg,
  faRedo as faRedoReg,
  faUser as faUserReg,
} from '@fortawesome/pro-regular-svg-icons'

// Solid
import {
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faBrain as faBrainSolid,
  faCalculator,
  faChevronDoubleRight,
  faTags,
  faSpinnerThird,
  faCalendarTimes,
  faCaretRight,
  faChartLine,
  faChartPie,
  faCheck,
  faCheckCircle,
  faComments,
  faQuestionCircle,
  faExclamationCircle,
  faExclamationTriangle,
  faInfoCircle,
  faPercentage,
  faPiggyBank,
  faEnvelope,
  faCreditCard,
  faCog,
  faUser as faUserSolid,
  faUserHeadset,
  faSearch,
} from '@fortawesome/pro-solid-svg-icons'

// duoTone
import {
  faAbacus as faAbacusDuo,
  faAnalytics as faAnalyticsDuo,
  faBadgeDollar as faBadgeDollarDuo,
  faBalanceScaleRight as faBalanceScaleRightDuo,
  faBrain as faBrainDuo,
  faComment as faCommentDuo,
  faCalculator as faCalculatorDuo,
  faCalendar as faCalendarDuo,
  faChartPie as faChartPieDuo,
  faChartLine as faChartLineDuo,
  faChartLineDown as faChartLineDownDuo,
  faCheckSquare as faCheckSquareDuo,
  faClock as faClockDuo,
  faComments as faCommentsDuo,
  faCreditCard as faCreditCardDuo,
  faEnvelope as faEnvelopeDuo,
  faExclamationSquare,
  faExclamationTriangle as faExclamationTriangleDuo,
  faGift as faGiftDuo,
  faHandHoldingUsd as faHandHoldingUsdDuo,
  faHandshake as faHandshakeDuo,
  faHourglassStart as faHourglassStartDuo,
  faInfoSquare as faInfoSquareDuo,
  faLockAlt as faLockAltDuo,
  faMoneyBillWave as faMoneyBillWaveDuo,
  faMoneyCheckEditAlt as faMoneyCheckEditAltDuo,
  faTools,
  faSignOutAlt,
  faHistory,
  faPause as faPauseDuo,
  faPauseCircle as faPauseCircleDuo,
  faPercent as faPercentDuo,
  faPercentage as faPercentageDuo,
  faPhoneAlt as faPhoneAltDuo,
  faUser as faUserDuo,
  faUserTie,
  faTimesOctagon as faTimesOctagonDuo,
} from '@fortawesome/pro-duotone-svg-icons'

// brands
import { faFacebookF, faTwitter, faLinkedin, faDiscord } from '@fortawesome/free-brands-svg-icons'

library.add(
  faAbacusDuo,
  faAnalytics,
  faAnalyticsDuo,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faBadgeDollarDuo,
  faBalanceScaleRightDuo,
  faBars,
  faBrain,
  faBrainDuo,
  faBrainSolid,
  faCalculator,
  faCalculatorDuo,
  faCalendarDuo,
  faCalendarTimes,
  faCaretRight,
  faChartLine,
  faChartLineDuo,
  faChartLineDownDuo,
  faChartPie,
  faChartPieDuo,
  faClockDuo,
  faCommentDuo,
  faCheck,
  faCheckCircle,
  faCheckSquareDuo,
  faChevronDoubleRight,
  faCog,
  faComments,
  faCommentsDuo,
  faCreditCard,
  faCreditCardDuo,
  faDiscord,
  faDollarSign,
  faEnvelopeReg,
  faEnvelope,
  faEnvelopeDuo,
  faExclamationCircle,
  faExclamationSquare,
  faExclamationTriangle,
  faExclamationTriangleDuo,
  faGiftDuo,
  faHandHoldingUsdDuo,
  faHandshakeDuo,
  faHistory,
  faHourglassStartDuo,
  faInfoCircle,
  faInfoSquareDuo,
  faInfoCircleReg,
  faInfoSquare,
  faLockAlt,
  faLockAltDuo,
  faMoneyCheckEditAltDuo,
  faPauseDuo,
  faPauseCircleDuo,
  faPercentDuo,
  faPercentageDuo,
  faPiggyBank,
  faPhoneAltDuo,
  faMoneyBillWaveDuo,
  faNewspaper,
  faPercent,
  faPercentage,
  faQuestionCircle,
  faQuestionCircleReg,
  faSignOutAlt,
  faSpinnerThird,
  faTags,
  faTagsReg,
  faTimes,
  faTimesOctagonDuo,
  faTools,
  faRedoReg,
  faUserDuo,
  faUserReg,
  faUserSolid,
  faUserTie,
  faUserHeadset,
  faSearch,
  faFacebookF,
  faTwitter,
  faLinkedin
)
