import { library } from '@fortawesome/fontawesome-svg-core'

// Regular
import {
  faAnalytics,
  faBars,
  faBrain,
  faEnvelope as faEnvelopeReg,
  faTimes,
  faPercent,
  faNewspaper,
  faLockAlt,
  faInfoSquare,
  faInfoCircle as faInfoCircleReg,
  faQuestionCircle as faQuestionCircleReg,
  faDollarSign,
  faTags as faTagsReg,
  faRedo as faRedoReg,
  faUser as faUserReg,
} from '@fortawesome/pro-regular-svg-icons'

// Solid
import {
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faBrain as faBrainSolid,
  faCalculator,
  faTags,
  faSpinnerThird,
  faCalendarTimes,
  faCaretRight,
  faChartLine,
  faChartPie,
  faCheck,
  faCheckCircle,
  faComments,
  faQuestionCircle,
  faExclamationCircle,
  faExclamationTriangle,
  faInfoCircle,
  faPercentage,
  faPiggyBank,
  faEnvelope,
  faCreditCard,
  faCog,
  faUser as faUserSolid,
  faUserHeadset,
  faSearch,
} from '@fortawesome/pro-solid-svg-icons'

// duoTone
import {
  faBadgeDollar as faBadgeDollarDuo,
  faBrain as faBrainDuo,
  faMoneyBillWave as faMoneyBillWaveDuo,
  faCalendar as faCalendarDuo,
  faChartPie as faChartPieDuo,
  faCheckSquare,
  faComments as faCommentsDuo,
  faCreditCard as faCreditCardDuo,
  faEnvelope as faEnvelopeDuo,
  faExclamationSquare,
  faExclamationTriangle as faExclamationTriangleDuo,
  faHourglassStart as faHourglassStartDuo,
  faLockAlt as faLockAltDuo,
  faTools,
  faSignOutAlt,
  faHistory,
  faChartLine as faChartLineDuo,
  faPause as faPauseDuo,
  faPauseCircle as faPauseCircleDuo,
  faPercent as faPercentDuo,
  faPercentage as faPercentageDuo,
  faPhoneAlt as faPhoneAltDuo,
  faUser as faUserDuo,
  faUserTie,
  faTimesOctagon as faTimesOctagonDuo,
} from '@fortawesome/pro-duotone-svg-icons'

// brands
import { faFacebookF, faTwitter, faLinkedin, faDiscord } from '@fortawesome/free-brands-svg-icons'

library.add(
  faAnalytics,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faBadgeDollarDuo,
  faBars,
  faBrain,
  faBrainDuo,
  faBrainSolid,
  faCalculator,
  faCalendarDuo,
  faCalendarTimes,
  faCaretRight,
  faChartLine,
  faChartLineDuo,
  faChartPie,
  faChartPieDuo,
  faCheck,
  faCheckCircle,
  faCheckSquare,
  faCog,
  faComments,
  faCommentsDuo,
  faCreditCard,
  faCreditCardDuo,
  faDiscord,
  faDollarSign,
  faEnvelopeReg,
  faEnvelope,
  faEnvelopeDuo,
  faExclamationCircle,
  faExclamationSquare,
  faExclamationTriangle,
  faExclamationTriangleDuo,
  faHistory,
  faHourglassStartDuo,
  faInfoCircle,
  faInfoCircleReg,
  faInfoSquare,
  faLockAlt,
  faLockAltDuo,
  faPauseDuo,
  faPauseCircleDuo,
  faPercentDuo,
  faPercentageDuo,
  faPiggyBank,
  faPhoneAltDuo,
  faMoneyBillWaveDuo,
  faNewspaper,
  faPercent,
  faPercentage,
  faQuestionCircle,
  faQuestionCircleReg,
  faSignOutAlt,
  faSpinnerThird,
  faTags,
  faTagsReg,
  faTimes,
  faTimesOctagonDuo,
  faTools,
  faRedoReg,
  faUserDuo,
  faUserReg,
  faUserSolid,
  faUserTie,
  faUserHeadset,
  faSearch,
  faFacebookF,
  faTwitter,
  faLinkedin
)
