export { default as StatisticsModal } from './Statistics'
export { default as AIScoreModal } from './AIScore'
export { default as ReturnsCalculatorModal } from './ReturnsCalculator'
export { default as LoginModal } from './Login'
export { default as SignupModal } from './Signup'
export { default as PastTradesModal } from './PastTrades'
