export default [
  { label: 'Afghanistan', value: 'AF', emoji: '🇦🇫' },
  { label: 'land Islands', value: 'AX', emoji: '🇦🇽' },
  { label: 'Albania', value: 'AL', taxPercent: 20, emoji: '🇦🇱' },
  { label: 'Algeria', value: 'DZ', emoji: '🇩🇿' },
  { label: 'American Samoa', value: 'AS', emoji: '🇦🇸' },
  { label: 'Andorra', value: 'AD', emoji: '🇦🇩' },
  { label: 'Angola', value: 'AO', emoji: '🇦🇴' },
  { label: 'Anguilla', value: 'AI', emoji: '🇦🇮' },
  { label: 'Antarctica', value: 'AQ', emoji: '🇦🇶' },
  { label: 'Antigua and Barbuda', value: 'AG', emoji: '🇦🇬' },
  { label: 'Argentina', value: 'AR', emoji: '🇦🇷' },
  { label: 'Armenia', value: 'AM', emoji: '🇦🇲' },
  { label: 'Aruba', value: 'AW', emoji: '🇦🇼' },
  { label: 'Australia', value: 'AU', emoji: '🇦🇺' },
  { label: 'Austria', value: 'AT', taxPercent: 20, emoji: '🇦🇹' },
  { label: 'Azerbaijan', value: 'AZ', emoji: '🇦🇿' },
  { label: 'Bahamas', value: 'BS', emoji: '🇧🇸' },
  { label: 'Bahrain', value: 'BH', emoji: '🇧🇭' },
  { label: 'Bangladesh', value: 'BD', emoji: '🇧🇩' },
  { label: 'Barbados', value: 'BB', emoji: '🇧🇧' },
  { label: 'Belarus', value: 'BY', taxPercent: 20, emoji: '🇧🇾' },
  { label: 'Belgium', value: 'BE', taxPercent: 21, emoji: '🇧🇪' },
  { label: 'Belize', value: 'BZ', emoji: '🇧🇿' },
  { label: 'Benin', value: 'BJ', emoji: '🇧🇯' },
  { label: 'Bermuda', value: 'BM', emoji: '🇧🇲' },
  { label: 'Bhutan', value: 'BT', emoji: '🇧🇹' },
  { label: 'Bolivia', value: 'BO', emoji: '🇧🇴' },
  { label: 'Bosnia and Herzegovina', value: 'BA', taxPercent: 17, emoji: '🇧🇦' },
  { label: 'Botswana', value: 'BW', emoji: '🇧🇼' },
  { label: 'Bouvet Island', value: 'BV', emoji: '🇧🇻' },
  { label: 'Brazil', value: 'BR', emoji: '🇧🇷' },
  { label: 'British Indian Ocean Territory', value: 'IO', emoji: '🇮🇴' },
  { label: 'Brunei Darussalam', value: 'BN', emoji: '🇧🇳' },
  { label: 'Bulgaria', value: 'BG', taxPercent: 20, emoji: '🇧🇬' },
  { label: 'Burkina Faso', value: 'BF', emoji: '🇧🇫' },
  { label: 'Burundi', value: 'BI', emoji: '🇧🇮' },
  { label: 'Cambodia', value: 'KH', emoji: '🇰🇭' },
  { label: 'Cameroon', value: 'CM', emoji: '🇨🇲' },
  { label: 'Canada', value: 'CA', emoji: '🇨🇦' },
  { label: 'Cape Verde', value: 'CV', emoji: '🇨🇻' },
  { label: 'Cayman Islands', value: 'KY', emoji: '🇰🇾' },
  { label: 'Central African Republic', value: 'CF', emoji: '🇨🇫' },
  { label: 'Chad', value: 'TD', emoji: '🇹🇩' },
  { label: 'Chile', value: 'CL', emoji: '🇨🇱' },
  { label: 'China', value: 'CN', emoji: '🇨🇳' },
  { label: 'Christmas Island', value: 'CX', emoji: '🇨🇽' },
  { label: 'Cocos (Keeling) Islands', value: 'CC', emoji: '🇨🇨' },
  { label: 'Colombia', value: 'CO', emoji: '🇨🇴' },
  { label: 'Comoros', value: 'KM', emoji: '🇰🇲' },
  { label: 'Congo', value: 'CG', emoji: '🇨🇬' },
  { label: 'Cook Islands', value: 'CK', emoji: '🇨🇰' },
  { label: 'Costa Rica', value: 'CR', emoji: '🇨🇷' },
  { label: "Cote D'Ivoire", value: 'CI', emoji: '🇨🇮' },
  { label: 'Croatia', value: 'HR', taxPercent: 25, emoji: '🇭🇷' },
  { label: 'Cuba', value: 'CU', emoji: '🇨🇺' },
  //   { label: 'Curaçao', value: '', emoji: '🇨🇼' },
  { label: 'Cyprus', value: 'CY', taxPercent: 19, emoji: '🇨🇾' },
  { label: 'Czechia', value: 'CZ', taxPercent: 21, emoji: '🇨🇿' },
  { label: 'Denmark', value: 'DK', taxPercent: 25, emoji: '🇩🇰' },
  { label: 'Djibouti', value: 'DJ', emoji: '🇩🇯' },
  { label: 'Dominica', value: 'DM', emoji: '🇩🇲' },
  { label: 'Dominican Republic', value: 'DO', emoji: '🇩🇴' },
  { label: 'Ecuador', value: 'EC', emoji: '🇪🇨' },
  { label: 'Egypt', value: 'EG', emoji: '🇪🇬' },
  { label: 'El Salvador', value: 'SV', emoji: '🇸🇻' },
  { label: 'Equatorial Guinea', value: 'GQ', emoji: '🇬🇶' },
  { label: 'Eritrea', value: 'ER', emoji: '🇪🇷' },
  { label: 'Estonia', value: 'EE', taxPercent: 20, emoji: '🇪🇪' },
  { label: 'Ethiopia', value: 'ET', emoji: '🇪🇹' },
  { label: 'Falkland Islands (Malvinas)', value: 'FK', emoji: '🇫🇰' },
  { label: 'Faroe Islands', value: 'FO', emoji: '🇫🇴' },
  { label: 'Fiji', value: 'FJ', emoji: '🇫🇯' },
  { label: 'Finland', value: 'FI', taxPercent: 24, emoji: '🇫🇮' },
  { label: 'France', value: 'FR', taxPercent: 20, emoji: '🇫🇷' },
  { label: 'French Guiana', value: 'GF', emoji: '🇬🇫' },
  { label: 'French Polynesia', value: 'PF', emoji: '🇵🇫' },
  { label: 'French Southern Territories', value: 'TF', emoji: '🇹🇫' },
  { label: 'Gabon', value: 'GA', emoji: '🇬🇦' },
  { label: 'Gambia', value: 'GM', emoji: '🇬🇲' },
  { label: 'Georgia', value: 'GE', emoji: '🇬🇪' },
  { label: 'Germany', value: 'DE', taxPercent: 19, emoji: '🇩🇪' },
  { label: 'Ghana', value: 'GH', emoji: '🇬🇭' },
  { label: 'Gibraltar', value: 'GI', emoji: '🇬🇮' },
  { label: 'Greece', value: 'GR', taxPercent: 24, emoji: '🇬🇷' },
  { label: 'Greenland', value: 'GL', emoji: '🇬🇱' },
  { label: 'Grenada', value: 'GD', emoji: '🇬🇩' },
  { label: 'Guadeloupe', value: 'GP', emoji: '🇬🇵' },
  { label: 'Guam', value: 'GU', emoji: '🇬🇺' },
  { label: 'Guatemala', value: 'GT', emoji: '🇬🇹' },
  { label: 'Guernsey', value: 'GG', emoji: '🇬🇬' },
  { label: 'Guinea', value: 'GN', emoji: '🇬🇳' },
  { label: 'Guinea-Bissau', value: 'GW', emoji: '🇬🇼' },
  { label: 'Guyana', value: 'GY', emoji: '🇬🇾' },
  { label: 'Haiti', value: 'HT', emoji: '🇭🇹' },
  { label: 'Heard Island and Mcdonald Islands', value: 'HM', emoji: '🇭🇲' },
  { label: 'Holy See (Vatican City State)', value: 'VA', emoji: '🇻🇦' },
  { label: 'Honduras', value: 'HN', emoji: '🇭🇳' },
  { label: 'Hong Kong', value: 'HK', emoji: '🇭🇰' },
  { label: 'Hungary', value: 'HU', taxPercent: 27, emoji: '🇭🇺' },
  { label: 'Iceland', value: 'IS', taxPercent: 24, emoji: '🇮🇸' },
  { label: 'India', value: 'IN', emoji: '🇮🇳' },
  { label: 'Indonesia', value: 'ID', emoji: '🇮🇩' },
  { label: 'Iran', value: 'IR', emoji: '🇮🇷' },
  { label: 'Iraq', value: 'IQ', emoji: '🇮🇶' },
  { label: 'Ireland', value: 'IE', taxPercent: 23, emoji: '🇮🇪' },
  { label: 'Isle of Man', value: 'IM', emoji: '🇮🇲' },
  { label: 'Israel', value: 'IL', emoji: '🇮🇱' },
  { label: 'Italy', value: 'IT', taxPercent: 22, emoji: '🇮🇹' },
  { label: 'Jamaica', value: 'JM', emoji: '🇯🇲' },
  { label: 'Japan', value: 'JP', emoji: '🇯🇵' },
  { label: 'Jersey', value: 'JE', emoji: '🇯🇪' },
  { label: 'Jordan', value: 'JO', emoji: '🇯🇴' },
  { label: 'Kazakhstan', value: 'KZ', emoji: '🇰🇿' },
  { label: 'Kenya', value: 'KE', emoji: '🇰🇪' },
  { label: 'Kiribati', value: 'KI', emoji: '🇰🇮' },
  { label: 'North Korea', value: 'KP', emoji: '🇰🇵' },
  { label: 'South Korea', value: 'KR', emoji: '🇰🇷' },
  { label: 'Kuwait', value: 'KW', emoji: '🇰🇼' },
  { label: 'Kyrgyzstan', value: 'KG', emoji: '🇰🇼' },
  { label: 'Lao', value: 'LA', emoji: '🇱🇦' },
  { label: 'Latvia', value: 'LV', taxPercent: 21, emoji: '🇱🇻' },
  { label: 'Lebanon', value: 'LB', emoji: '🇱🇧' },
  { label: 'Lesotho', value: 'LS', emoji: '🇱🇸' },
  { label: 'Liberia', value: 'LR', emoji: '🇱🇷' },
  { label: 'Libya', value: 'LY', emoji: '🇱🇾' },
  { label: 'Liechtenstein', value: 'LI', taxPercent: 8, emoji: '🇱🇮' },
  { label: 'Lithuania', value: 'LT', taxPercent: 21, emoji: '🇱🇹' },
  { label: 'Luxembourg', value: 'LU', taxPercent: 17, emoji: '🇱🇺' },
  { label: 'Macau', value: 'MO', emoji: '🇲🇴' },
  { label: 'Macedonia', value: 'MK', taxPercent: 18, emoji: '🇲🇰' },
  { label: 'Madagascar', value: 'MG', emoji: '🇲🇬' },
  { label: 'Malawi', value: 'MW', emoji: '🇲🇼' },
  { label: 'Malaysia', value: 'MY', emoji: '🇲🇾' },
  { label: 'Maldives', value: 'MV', emoji: '🇲🇻' },
  { label: 'Mali', value: 'ML', emoji: '🇲🇱' },
  { label: 'Malta', value: 'MT', taxPercent: 18, emoji: '🇲🇹' },
  { label: 'Marshall Islands', value: 'MH', emoji: '🇲🇭' },
  { label: 'Martinique', value: 'MQ', emoji: '🇲🇶' },
  { label: 'Mauritania', value: 'MR', emoji: '🇲🇷' },
  { label: 'Mauritius', value: 'MU', emoji: '🇲🇺' },
  { label: 'Mayotte', value: 'YT', emoji: '🇾🇹' },
  { label: 'Mexico', value: 'MX', emoji: '🇲🇽' },
  { label: 'Micronesia', value: 'FM', emoji: '🇫🇲' },
  { label: 'Moldova', value: 'MD', emoji: '🇲🇩' },
  { label: 'Monaco', value: 'MC', emoji: '🇲🇨' },
  { label: 'Mongolia', value: 'MN', emoji: '🇲🇳' },
  { label: 'Montenegro', value: 'ME', taxPercent: 17, emoji: '🇲🇪' },
  { label: 'Montserrat', value: 'MS', emoji: '🇲🇸' },
  { label: 'Morocco', value: 'MA', emoji: '🇲🇦' },
  { label: 'Mozambique', value: 'MZ', emoji: '🇲🇿' },
  { label: 'Myanmar', value: 'MM', emoji: '🇲🇲' },
  { label: 'Namibia', value: 'NA', emoji: '🇳🇦' },
  { label: 'Nauru', value: 'NR', emoji: '🇳🇷' },
  { label: 'Nepal', value: 'NP', emoji: '🇳🇵' },
  { label: 'Netherlands', value: 'NL', taxPercent: 21, emoji: '🇳🇱' },
  { label: 'New Caledonia', value: 'NC', emoji: '🇳🇨' },
  { label: 'New Zealand', value: 'NZ', emoji: '🇳🇿' },
  { label: 'Nicaragua', value: 'NI', emoji: '🇳🇮' },
  { label: 'Niger', value: 'NE', emoji: '🇳🇪' },
  { label: 'Nigeria', value: 'NG', emoji: '🇳🇬' },
  { label: 'Niue', value: 'NU', emoji: '🇳🇺' },
  { label: 'Norfolk Island', value: 'NF', emoji: '🇳🇫' },
  { label: 'Northern Mariana Islands', value: 'MP', emoji: '🇲🇵' },
  { label: 'Norway', value: 'NO', taxPercent: 25, emoji: '🇳🇴' },
  { label: 'Oman', value: 'OM', emoji: '🇴🇲' },
  { label: 'Pakistan', value: 'PK', emoji: '🇵🇰' },
  { label: 'Palau', value: 'PW', emoji: '🇵🇼' },
  { label: 'Palestine', value: 'PS', emoji: '🇵🇸' },
  { label: 'Panama', value: 'PA', emoji: '🇵🇦' },
  { label: 'Papua New Guinea', value: 'PG', emoji: '🇵🇬' },
  { label: 'Paraguay', value: 'PY', emoji: '🇵🇾' },
  { label: 'Peru', value: 'PE', emoji: '🇵🇪' },
  { label: 'Philippines', value: 'PH', emoji: '🇵🇭' },
  { label: 'Pitcairn', value: 'PN', emoji: '🇵🇳' },
  { label: 'Poland', value: 'PL', taxPercent: 23, emoji: '🇵🇱' },
  { label: 'Portugal', value: 'PT', emoji: '🇵🇹' },
  { label: 'Puerto Rico', value: 'PR', emoji: '🇵🇷' },
  { label: 'Qatar', value: 'QA', emoji: '🇶🇦' },
  { label: 'Reunion', value: 'RE', emoji: '🇷🇪' },
  { label: 'Romania', value: 'RO', taxPercent: 20, emoji: '🇷🇴' },
  { label: 'Russian Federation', value: 'RU', emoji: '🇷🇺' },
  { label: 'Rwanda', value: 'RW', emoji: '🇷🇼' },
  { label: 'Saint Helena', value: 'SH', emoji: '🇸🇭' },
  { label: 'Saint Kitts and Nevis', value: 'KN', emoji: '🇰🇳' },
  { label: 'Saint Lucia', value: 'LC', emoji: '🇱🇨' },
  { label: 'Saint Pierre and Miquelon', value: 'PM', emoji: '🇵🇲' },
  { label: 'Saint Vincent and the Grenadines', value: 'VC', emoji: '🇻🇨' },
  { label: 'Samoa', value: 'WS', emoji: '🇼🇸' },
  { label: 'San Marino', value: 'SM', emoji: '🇸🇲' },
  { label: 'Sao Tome and Principe', value: 'ST', emoji: '🇸🇹' },
  { label: 'Saudi Arabia', value: 'SA', emoji: '🇸🇦' },
  { label: 'Senegal', value: 'SN', emoji: '🇸🇳' },
  { label: 'Serbia', value: 'RS', taxPercent: 20, emoji: '🇷🇸' },
  { label: 'Seychelles', value: 'SC', emoji: '🇸🇨' },
  { label: 'Sierra Leone', value: 'SL', emoji: '🇸🇱' },
  { label: 'Singapore', value: 'SG', emoji: '🇸🇬' },
  { label: 'Slovakia', value: 'SK', emoji: '🇸🇰' },
  { label: 'Slovenia', value: 'SI', taxPercent: 22, emoji: '🇸🇮' },
  { label: 'Solomon Islands', value: 'SB', emoji: '🇸🇧' },
  { label: 'Somalia', value: 'SO', emoji: '🇸🇴' },
  { label: 'South Africa', value: 'ZA', emoji: '🇿🇦' },
  { label: 'South Georgia', value: 'GS', emoji: '🇬🇸' },
  { label: 'Spain', value: 'ES', taxPercent: 21, emoji: '🇪🇸' },
  { label: 'Sri Lanka', value: 'LK', emoji: '🇱🇰' },
  { label: 'Sudan', value: 'SD', emoji: '🇸🇸' },
  { label: 'Suriname', value: 'SR', emoji: '🇸🇷' },
  { label: 'Svalbard and Jan Mayen', value: 'SJ', emoji: '🇸🇯' },
  { label: 'Swaziland', value: 'SZ', emoji: '🇸🇿' },
  { label: 'Sweden', value: 'SE', taxPercent: 25, emoji: '🇸🇪' },
  { label: 'Switzerland', value: 'CH', taxPercent: 8, emoji: '🇨🇭' },
  { label: 'Syria', value: 'SY', emoji: '🇸🇾' },
  { label: 'Taiwan', value: 'TW', emoji: '🇹🇼' },
  { label: 'Tajikistan', value: 'TJ', emoji: '🇹🇯' },
  { label: 'Tanzania', value: 'TZ', emoji: '🇹🇿' },
  { label: 'Thailand', value: 'TH', emoji: '🇹🇭' },
  { label: 'Timor-Leste', value: 'TL', emoji: '🇹🇱' },
  { label: 'Togo', value: 'TG', emoji: '🇹🇬' },
  { label: 'Tokelau', value: 'TK', emoji: '🇹🇰' },
  { label: 'Tonga', value: 'TO', emoji: '🇹🇴' },
  { label: 'Trinidad and Tobago', value: 'TT', emoji: '🇹🇹' },
  { label: 'Tunisia', value: 'TN', emoji: '🇹🇳' },
  { label: 'Turkey', value: 'TR', emoji: '🇹🇷' },
  { label: 'Turkmenistan', value: 'TM', emoji: '🇹🇲' },
  { label: 'Turks and Caicos Islands', value: 'TC', emoji: '🇹🇨' },
  { label: 'Tuvalu', value: 'TV', emoji: '🇹🇻' },
  { label: 'Uganda', value: 'UG', emoji: '🇺🇬' },
  { label: 'Ukraine', value: 'UA', taxPercent: 20, emoji: '🇺🇦' },
  { label: 'United Arab Emirates', value: 'AE', emoji: '🇦🇪' },
  { label: 'United Kingdom', value: 'GB', taxPercent: 20, emoji: '🇬🇧' },
  { label: 'United States', value: 'US', emoji: '🇺🇸' },
  { label: 'United States Minor Outlying Islands', value: 'UM', emoji: '🇺🇲' },
  { label: 'Uruguay', value: 'UY', emoji: '🇺🇾' },
  { label: 'Uzbekistan', value: 'UZ', emoji: '🇺🇿' },
  { label: 'Vanuatu', value: 'VU', emoji: '🇻🇺' },
  { label: 'Venezuela', value: 'VE', emoji: '🇻🇪' },
  { label: 'Vietnam', value: 'VN', emoji: '🇻🇳' },
  { label: 'British Virgin Islands', value: 'VG', emoji: '🇻🇬' },
  { label: 'U.S. Virgin Islands', value: 'VI', emoji: '🇻🇮' },
  { label: 'Wallis and Futuna', value: 'WF', emoji: '🇼🇫' },
  { label: 'Western Sahara', value: 'EH', emoji: '🇪🇭' },
  { label: 'Yemen', value: 'YE', emoji: '🇾🇪' },
  { label: 'Zambia', value: 'ZM', emoji: '🇿🇲' },
  { label: 'Zimbabwe', value: 'ZW', emoji: '🇿🇼' },
]
