export default {
  AF: {
    country: 'Afghanistan',
    countryCode: 'AF',
    emoji: '🇦🇫',
  },
  AX: {
    country: 'land Islands',
    countryCode: 'AX',
    emoji: '🇦🇽',
  },
  AL: {
    country: 'Albania',
    countryCode: 'AL',
    taxPercent: 20,
    emoji: '🇦🇱',
  },
  DZ: {
    country: 'Algeria',
    countryCode: 'DZ',
    emoji: '🇩🇿',
  },
  AS: {
    country: 'American Samoa',
    countryCode: 'AS',
    emoji: '🇦🇸',
  },
  AD: {
    country: 'Andorra',
    countryCode: 'AD',
    emoji: '🇦🇩',
  },
  AO: {
    country: 'Angola',
    countryCode: 'AO',
    emoji: '🇦🇴',
  },
  AI: {
    country: 'Anguilla',
    countryCode: 'AI',
    emoji: '🇦🇮',
  },
  AQ: {
    country: 'Antarctica',
    countryCode: 'AQ',
    emoji: '🇦🇶',
  },
  AG: {
    country: 'Antigua and Barbuda',
    countryCode: 'AG',
    emoji: '🇦🇬',
  },
  AR: {
    country: 'Argentina',
    countryCode: 'AR',
    emoji: '🇦🇷',
  },
  AM: {
    country: 'Armenia',
    countryCode: 'AM',
    emoji: '🇦🇲',
  },
  AW: {
    country: 'Aruba',
    countryCode: 'AW',
    emoji: '🇦🇼',
  },
  AU: {
    country: 'Australia',
    countryCode: 'AU',
    emoji: '🇦🇺',
  },
  AT: {
    country: 'Austria',
    countryCode: 'AT',
    taxPercent: 20,
    emoji: '🇦🇹',
  },
  AZ: {
    country: 'Azerbaijan',
    countryCode: 'AZ',
    emoji: '🇦🇿',
  },
  BS: {
    country: 'Bahamas',
    countryCode: 'BS',
    emoji: '🇧🇸',
  },
  BH: {
    country: 'Bahrain',
    countryCode: 'BH',
    emoji: '🇧🇭',
  },
  BD: {
    country: 'Bangladesh',
    countryCode: 'BD',
    emoji: '🇧🇩',
  },
  BB: {
    country: 'Barbados',
    countryCode: 'BB',
    emoji: '🇧🇧',
  },
  BY: {
    country: 'Belarus',
    countryCode: 'BY',
    taxPercent: 20,
    emoji: '🇧🇾',
  },
  BE: {
    country: 'Belgium',
    countryCode: 'BE',
    taxPercent: 21,
    emoji: '🇧🇪',
  },
  BZ: {
    country: 'Belize',
    countryCode: 'BZ',
    emoji: '🇧🇿',
  },
  BJ: {
    country: 'Benin',
    countryCode: 'BJ',
    emoji: '🇧🇯',
  },
  BM: {
    country: 'Bermuda',
    countryCode: 'BM',
    emoji: '🇧🇲',
  },
  BT: {
    country: 'Bhutan',
    countryCode: 'BT',
    emoji: '🇧🇹',
  },
  BO: {
    country: 'Bolivia',
    countryCode: 'BO',
    emoji: '🇧🇴',
  },
  BA: {
    country: 'Bosnia and Herzegovina',
    countryCode: 'BA',
    taxPercent: 17,
    emoji: '🇧🇦',
  },
  BW: {
    country: 'Botswana',
    countryCode: 'BW',
    emoji: '🇧🇼',
  },
  BV: {
    country: 'Bouvet Island',
    countryCode: 'BV',
    emoji: '🇧🇻',
  },
  BR: {
    country: 'Brazil',
    countryCode: 'BR',
    emoji: '🇧🇷',
  },
  IO: {
    country: 'British Indian Ocean Territory',
    countryCode: 'IO',
    emoji: '🇮🇴',
  },
  BN: {
    country: 'Brunei Darussalam',
    countryCode: 'BN',
    emoji: '🇧🇳',
  },
  BG: {
    country: 'Bulgaria',
    countryCode: 'BG',
    taxPercent: 20,
    emoji: '🇧🇬',
  },
  BF: {
    country: 'Burkina Faso',
    countryCode: 'BF',
    emoji: '🇧🇫',
  },
  BI: {
    country: 'Burundi',
    countryCode: 'BI',
    emoji: '🇧🇮',
  },
  KH: {
    country: 'Cambodia',
    countryCode: 'KH',
    emoji: '🇰🇭',
  },
  CM: {
    country: 'Cameroon',
    countryCode: 'CM',
    emoji: '🇨🇲',
  },
  CA: {
    country: 'Canada',
    countryCode: 'CA',
    emoji: '🇨🇦',
  },
  CV: {
    country: 'Cape Verde',
    countryCode: 'CV',
    emoji: '🇨🇻',
  },
  KY: {
    country: 'Cayman Islands',
    countryCode: 'KY',
    emoji: '🇰🇾',
  },
  CF: {
    country: 'Central African Republic',
    countryCode: 'CF',
    emoji: '🇨🇫',
  },
  TD: {
    country: 'Chad',
    countryCode: 'TD',
    emoji: '🇹🇩',
  },
  CL: {
    country: 'Chile',
    countryCode: 'CL',
    emoji: '🇨🇱',
  },
  CN: {
    country: 'China',
    countryCode: 'CN',
    emoji: '🇨🇳',
  },
  CX: {
    country: 'Christmas Island',
    countryCode: 'CX',
    emoji: '🇨🇽',
  },
  CC: {
    country: 'Cocos (Keeling) Islands',
    countryCode: 'CC',
    emoji: '🇨🇨',
  },
  CO: {
    country: 'Colombia',
    countryCode: 'CO',
    emoji: '🇨🇴',
  },
  KM: {
    country: 'Comoros',
    countryCode: 'KM',
    emoji: '🇰🇲',
  },
  CG: {
    country: 'Congo',
    countryCode: 'CG',
    emoji: '🇨🇬',
  },
  CK: {
    country: 'Cook Islands',
    countryCode: 'CK',
    emoji: '🇨🇰',
  },
  CR: {
    country: 'Costa Rica',
    countryCode: 'CR',
    emoji: '🇨🇷',
  },
  CI: {
    country: "Cote D'Ivoire",
    countryCode: 'CI',
    emoji: '🇨🇮',
  },
  HR: {
    country: 'Croatia',
    countryCode: 'HR',
    taxPercent: 25,
    emoji: '🇭🇷',
  },
  CU: {
    country: 'Cuba',
    countryCode: 'CU',
    emoji: '🇨🇺',
  },
  CY: {
    country: 'Cyprus',
    countryCode: 'CY',
    taxPercent: 19,
    emoji: '🇨🇾',
  },
  CZ: {
    country: 'Czechia',
    countryCode: 'CZ',
    taxPercent: 21,
    emoji: '🇨🇿',
  },
  DK: {
    country: 'Denmark',
    countryCode: 'DK',
    taxPercent: 25,
    emoji: '🇩🇰',
  },
  DJ: {
    country: 'Djibouti',
    countryCode: 'DJ',
    emoji: '🇩🇯',
  },
  DM: {
    country: 'Dominica',
    countryCode: 'DM',
    emoji: '🇩🇲',
  },
  DO: {
    country: 'Dominican Republic',
    countryCode: 'DO',
    emoji: '🇩🇴',
  },
  EC: {
    country: 'Ecuador',
    countryCode: 'EC',
    emoji: '🇪🇨',
  },
  EG: {
    country: 'Egypt',
    countryCode: 'EG',
    emoji: '🇪🇬',
  },
  SV: {
    country: 'El Salvador',
    countryCode: 'SV',
    emoji: '🇸🇻',
  },
  GQ: {
    country: 'Equatorial Guinea',
    countryCode: 'GQ',
    emoji: '🇬🇶',
  },
  ER: {
    country: 'Eritrea',
    countryCode: 'ER',
    emoji: '🇪🇷',
  },
  EE: {
    country: 'Estonia',
    countryCode: 'EE',
    taxPercent: 20,
    emoji: '🇪🇪',
  },
  ET: {
    country: 'Ethiopia',
    countryCode: 'ET',
    emoji: '🇪🇹',
  },
  FK: {
    country: 'Falkland Islands (Malvinas)',
    countryCode: 'FK',
    emoji: '🇫🇰',
  },
  FO: {
    country: 'Faroe Islands',
    countryCode: 'FO',
    emoji: '🇫🇴',
  },
  FJ: {
    country: 'Fiji',
    countryCode: 'FJ',
    emoji: '🇫🇯',
  },
  FI: {
    country: 'Finland',
    countryCode: 'FI',
    taxPercent: 24,
    emoji: '🇫🇮',
  },
  FR: {
    country: 'France',
    countryCode: 'FR',
    taxPercent: 20,
    emoji: '🇫🇷',
  },
  GF: {
    country: 'French Guiana',
    countryCode: 'GF',
    emoji: '🇬🇫',
  },
  PF: {
    country: 'French Polynesia',
    countryCode: 'PF',
    emoji: '🇵🇫',
  },
  TF: {
    country: 'French Southern Territories',
    countryCode: 'TF',
    emoji: '🇹🇫',
  },
  GA: {
    country: 'Gabon',
    countryCode: 'GA',
    emoji: '🇬🇦',
  },
  GM: {
    country: 'Gambia',
    countryCode: 'GM',
    emoji: '🇬🇲',
  },
  GE: {
    country: 'Georgia',
    countryCode: 'GE',
    emoji: '🇬🇪',
  },
  DE: {
    country: 'Germany',
    countryCode: 'DE',
    taxPercent: 19,
    emoji: '🇩🇪',
  },
  GH: {
    country: 'Ghana',
    countryCode: 'GH',
    emoji: '🇬🇭',
  },
  GI: {
    country: 'Gibraltar',
    countryCode: 'GI',
    emoji: '🇬🇮',
  },
  GR: {
    country: 'Greece',
    countryCode: 'GR',
    taxPercent: 24,
    emoji: '🇬🇷',
  },
  GL: {
    country: 'Greenland',
    countryCode: 'GL',
    emoji: '🇬🇱',
  },
  GD: {
    country: 'Grenada',
    countryCode: 'GD',
    emoji: '🇬🇩',
  },
  GP: {
    country: 'Guadeloupe',
    countryCode: 'GP',
    emoji: '🇬🇵',
  },
  GU: {
    country: 'Guam',
    countryCode: 'GU',
    emoji: '🇬🇺',
  },
  GT: {
    country: 'Guatemala',
    countryCode: 'GT',
    emoji: '🇬🇹',
  },
  GG: {
    country: 'Guernsey',
    countryCode: 'GG',
    emoji: '🇬🇬',
  },
  GN: {
    country: 'Guinea',
    countryCode: 'GN',
    emoji: '🇬🇳',
  },
  GW: {
    country: 'Guinea-Bissau',
    countryCode: 'GW',
    emoji: '🇬🇼',
  },
  GY: {
    country: 'Guyana',
    countryCode: 'GY',
    emoji: '🇬🇾',
  },
  HT: {
    country: 'Haiti',
    countryCode: 'HT',
    emoji: '🇭🇹',
  },
  HM: {
    country: 'Heard Island and Mcdonald Islands',
    countryCode: 'HM',
    emoji: '🇭🇲',
  },
  VA: {
    country: 'Holy See (Vatican City State)',
    countryCode: 'VA',
    emoji: '🇻🇦',
  },
  HN: {
    country: 'Honduras',
    countryCode: 'HN',
    emoji: '🇭🇳',
  },
  HK: {
    country: 'Hong Kong',
    countryCode: 'HK',
    emoji: '🇭🇰',
  },
  HU: {
    country: 'Hungary',
    countryCode: 'HU',
    taxPercent: 27,
    emoji: '🇭🇺',
  },
  IS: {
    country: 'Iceland',
    countryCode: 'IS',
    taxPercent: 24,
    emoji: '🇮🇸',
  },
  IN: {
    country: 'India',
    countryCode: 'IN',
    emoji: '🇮🇳',
  },
  ID: {
    country: 'Indonesia',
    countryCode: 'ID',
    emoji: '🇮🇩',
  },
  IR: {
    country: 'Iran',
    countryCode: 'IR',
    emoji: '🇮🇷',
  },
  IQ: {
    country: 'Iraq',
    countryCode: 'IQ',
    emoji: '🇮🇶',
  },
  IE: {
    country: 'Ireland',
    countryCode: 'IE',
    taxPercent: 23,
    emoji: '🇮🇪',
  },
  IM: {
    country: 'Isle of Man',
    countryCode: 'IM',
    emoji: '🇮🇲',
  },
  IL: {
    country: 'Israel',
    countryCode: 'IL',
    emoji: '🇮🇱',
  },
  IT: {
    country: 'Italy',
    countryCode: 'IT',
    taxPercent: 22,
    emoji: '🇮🇹',
  },
  JM: {
    country: 'Jamaica',
    countryCode: 'JM',
    emoji: '🇯🇲',
  },
  JP: {
    country: 'Japan',
    countryCode: 'JP',
    emoji: '🇯🇵',
  },
  JE: {
    country: 'Jersey',
    countryCode: 'JE',
    emoji: '🇯🇪',
  },
  JO: {
    country: 'Jordan',
    countryCode: 'JO',
    emoji: '🇯🇴',
  },
  KZ: {
    country: 'Kazakhstan',
    countryCode: 'KZ',
    emoji: '🇰🇿',
  },
  KE: {
    country: 'Kenya',
    countryCode: 'KE',
    emoji: '🇰🇪',
  },
  KI: {
    country: 'Kiribati',
    countryCode: 'KI',
    emoji: '🇰🇮',
  },
  KP: {
    country: 'North Korea',
    countryCode: 'KP',
    emoji: '🇰🇵',
  },
  KR: {
    country: 'South Korea',
    countryCode: 'KR',
    emoji: '🇰🇷',
  },
  KW: {
    country: 'Kuwait',
    countryCode: 'KW',
    emoji: '🇰🇼',
  },
  KG: {
    country: 'Kyrgyzstan',
    countryCode: 'KG',
    emoji: '🇰🇼',
  },
  LA: {
    country: 'Lao',
    countryCode: 'LA',
    emoji: '🇱🇦',
  },
  LV: {
    country: 'Latvia',
    countryCode: 'LV',
    taxPercent: 21,
    emoji: '🇱🇻',
  },
  LB: {
    country: 'Lebanon',
    countryCode: 'LB',
    emoji: '🇱🇧',
  },
  LS: {
    country: 'Lesotho',
    countryCode: 'LS',
    emoji: '🇱🇸',
  },
  LR: {
    country: 'Liberia',
    countryCode: 'LR',
    emoji: '🇱🇷',
  },
  LY: {
    country: 'Libya',
    countryCode: 'LY',
    emoji: '🇱🇾',
  },
  LI: {
    country: 'Liechtenstein',
    countryCode: 'LI',
    taxPercent: 8,
    emoji: '🇱🇮',
  },
  LT: {
    country: 'Lithuania',
    countryCode: 'LT',
    taxPercent: 21,
    emoji: '🇱🇹',
  },
  LU: {
    country: 'Luxembourg',
    countryCode: 'LU',
    taxPercent: 17,
    emoji: '🇱🇺',
  },
  MO: {
    country: 'Macau',
    countryCode: 'MO',
    emoji: '🇲🇴',
  },
  MK: {
    country: 'Macedonia',
    countryCode: 'MK',
    taxPercent: 18,
    emoji: '🇲🇰',
  },
  MG: {
    country: 'Madagascar',
    countryCode: 'MG',
    emoji: '🇲🇬',
  },
  MW: {
    country: 'Malawi',
    countryCode: 'MW',
    emoji: '🇲🇼',
  },
  MY: {
    country: 'Malaysia',
    countryCode: 'MY',
    emoji: '🇲🇾',
  },
  MV: {
    country: 'Maldives',
    countryCode: 'MV',
    emoji: '🇲🇻',
  },
  ML: {
    country: 'Mali',
    countryCode: 'ML',
    emoji: '🇲🇱',
  },
  MT: {
    country: 'Malta',
    countryCode: 'MT',
    taxPercent: 18,
    emoji: '🇲🇹',
  },
  MH: {
    country: 'Marshall Islands',
    countryCode: 'MH',
    emoji: '🇲🇭',
  },
  MQ: {
    country: 'Martinique',
    countryCode: 'MQ',
    emoji: '🇲🇶',
  },
  MR: {
    country: 'Mauritania',
    countryCode: 'MR',
    emoji: '🇲🇷',
  },
  MU: {
    country: 'Mauritius',
    countryCode: 'MU',
    emoji: '🇲🇺',
  },
  YT: {
    country: 'Mayotte',
    countryCode: 'YT',
    emoji: '🇾🇹',
  },
  MX: {
    country: 'Mexico',
    countryCode: 'MX',
    emoji: '🇲🇽',
  },
  FM: {
    country: 'Micronesia',
    countryCode: 'FM',
    emoji: '🇫🇲',
  },
  MD: {
    country: 'Moldova',
    countryCode: 'MD',
    emoji: '🇲🇩',
  },
  MC: {
    country: 'Monaco',
    countryCode: 'MC',
    emoji: '🇲🇨',
  },
  MN: {
    country: 'Mongolia',
    countryCode: 'MN',
    emoji: '🇲🇳',
  },
  ME: {
    country: 'Montenegro',
    countryCode: 'ME',
    taxPercent: 17,
    emoji: '🇲🇪',
  },
  MS: {
    country: 'Montserrat',
    countryCode: 'MS',
    emoji: '🇲🇸',
  },
  MA: {
    country: 'Morocco',
    countryCode: 'MA',
    emoji: '🇲🇦',
  },
  MZ: {
    country: 'Mozambique',
    countryCode: 'MZ',
    emoji: '🇲🇿',
  },
  MM: {
    country: 'Myanmar',
    countryCode: 'MM',
    emoji: '🇲🇲',
  },
  NA: {
    country: 'Namibia',
    countryCode: 'NA',
    emoji: '🇳🇦',
  },
  NR: {
    country: 'Nauru',
    countryCode: 'NR',
    emoji: '🇳🇷',
  },
  NP: {
    country: 'Nepal',
    countryCode: 'NP',
    emoji: '🇳🇵',
  },
  NL: {
    country: 'Netherlands',
    countryCode: 'NL',
    taxPercent: 21,
    emoji: '🇳🇱',
  },
  NC: {
    country: 'New Caledonia',
    countryCode: 'NC',
    emoji: '🇳🇨',
  },
  NZ: {
    country: 'New Zealand',
    countryCode: 'NZ',
    emoji: '🇳🇿',
  },
  NI: {
    country: 'Nicaragua',
    countryCode: 'NI',
    emoji: '🇳🇮',
  },
  NE: {
    country: 'Niger',
    countryCode: 'NE',
    emoji: '🇳🇪',
  },
  NG: {
    country: 'Nigeria',
    countryCode: 'NG',
    emoji: '🇳🇬',
  },
  NU: {
    country: 'Niue',
    countryCode: 'NU',
    emoji: '🇳🇺',
  },
  NF: {
    country: 'Norfolk Island',
    countryCode: 'NF',
    emoji: '🇳🇫',
  },
  MP: {
    country: 'Northern Mariana Islands',
    countryCode: 'MP',
    emoji: '🇲🇵',
  },
  NO: {
    country: 'Norway',
    countryCode: 'NO',
    taxPercent: 25,
    emoji: '🇳🇴',
  },
  OM: {
    country: 'Oman',
    countryCode: 'OM',
    emoji: '🇴🇲',
  },
  PK: {
    country: 'Pakistan',
    countryCode: 'PK',
    emoji: '🇵🇰',
  },
  PW: {
    country: 'Palau',
    countryCode: 'PW',
    emoji: '🇵🇼',
  },
  PS: {
    country: 'Palestine',
    countryCode: 'PS',
    emoji: '🇵🇸',
  },
  PA: {
    country: 'Panama',
    countryCode: 'PA',
    emoji: '🇵🇦',
  },
  PG: {
    country: 'Papua New Guinea',
    countryCode: 'PG',
    emoji: '🇵🇬',
  },
  PY: {
    country: 'Paraguay',
    countryCode: 'PY',
    emoji: '🇵🇾',
  },
  PE: {
    country: 'Peru',
    countryCode: 'PE',
    emoji: '🇵🇪',
  },
  PH: {
    country: 'Philippines',
    countryCode: 'PH',
    emoji: '🇵🇭',
  },
  PN: {
    country: 'Pitcairn',
    countryCode: 'PN',
    emoji: '🇵🇳',
  },
  PL: {
    country: 'Poland',
    countryCode: 'PL',
    taxPercent: 23,
    emoji: '🇵🇱',
  },
  PT: {
    country: 'Portugal',
    countryCode: 'PT',
    emoji: '🇵🇹',
  },
  PR: {
    country: 'Puerto Rico',
    countryCode: 'PR',
    emoji: '🇵🇷',
  },
  QA: {
    country: 'Qatar',
    countryCode: 'QA',
    emoji: '🇶🇦',
  },
  RE: {
    country: 'Reunion',
    countryCode: 'RE',
    emoji: '🇷🇪',
  },
  RO: {
    country: 'Romania',
    countryCode: 'RO',
    taxPercent: 20,
    emoji: '🇷🇴',
  },
  RU: {
    country: 'Russian Federation',
    countryCode: 'RU',
    emoji: '🇷🇺',
  },
  RW: {
    country: 'Rwanda',
    countryCode: 'RW',
    emoji: '🇷🇼',
  },
  SH: {
    country: 'Saint Helena',
    countryCode: 'SH',
    emoji: '🇸🇭',
  },
  KN: {
    country: 'Saint Kitts and Nevis',
    countryCode: 'KN',
    emoji: '🇰🇳',
  },
  LC: {
    country: 'Saint Lucia',
    countryCode: 'LC',
    emoji: '🇱🇨',
  },
  PM: {
    country: 'Saint Pierre and Miquelon',
    countryCode: 'PM',
    emoji: '🇵🇲',
  },
  VC: {
    country: 'Saint Vincent and the Grenadines',
    countryCode: 'VC',
    emoji: '🇻🇨',
  },
  WS: {
    country: 'Samoa',
    countryCode: 'WS',
    emoji: '🇼🇸',
  },
  SM: {
    country: 'San Marino',
    countryCode: 'SM',
    emoji: '🇸🇲',
  },
  ST: {
    country: 'Sao Tome and Principe',
    countryCode: 'ST',
    emoji: '🇸🇹',
  },
  SA: {
    country: 'Saudi Arabia',
    countryCode: 'SA',
    emoji: '🇸🇦',
  },
  SN: {
    country: 'Senegal',
    countryCode: 'SN',
    emoji: '🇸🇳',
  },
  RS: {
    country: 'Serbia',
    countryCode: 'RS',
    taxPercent: 20,
    emoji: '🇷🇸',
  },
  SC: {
    country: 'Seychelles',
    countryCode: 'SC',
    emoji: '🇸🇨',
  },
  SL: {
    country: 'Sierra Leone',
    countryCode: 'SL',
    emoji: '🇸🇱',
  },
  SG: {
    country: 'Singapore',
    countryCode: 'SG',
    emoji: '🇸🇬',
  },
  SK: {
    country: 'Slovakia',
    countryCode: 'SK',
    emoji: '🇸🇰',
  },
  SI: {
    country: 'Slovenia',
    countryCode: 'SI',
    taxPercent: 22,
    emoji: '🇸🇮',
  },
  SB: {
    country: 'Solomon Islands',
    countryCode: 'SB',
    emoji: '🇸🇧',
  },
  SO: {
    country: 'Somalia',
    countryCode: 'SO',
    emoji: '🇸🇴',
  },
  ZA: {
    country: 'South Africa',
    countryCode: 'ZA',
    emoji: '🇿🇦',
  },
  GS: {
    country: 'South Georgia',
    countryCode: 'GS',
    emoji: '🇬🇸',
  },
  ES: {
    country: 'Spain',
    countryCode: 'ES',
    taxPercent: 21,
    emoji: '🇪🇸',
  },
  LK: {
    country: 'Sri Lanka',
    countryCode: 'LK',
    emoji: '🇱🇰',
  },
  SD: {
    country: 'Sudan',
    countryCode: 'SD',
    emoji: '🇸🇸',
  },
  SR: {
    country: 'Suriname',
    countryCode: 'SR',
    emoji: '🇸🇷',
  },
  SJ: {
    country: 'Svalbard and Jan Mayen',
    countryCode: 'SJ',
    emoji: '🇸🇯',
  },
  SZ: {
    country: 'Swaziland',
    countryCode: 'SZ',
    emoji: '🇸🇿',
  },
  SE: {
    country: 'Sweden',
    countryCode: 'SE',
    taxPercent: 25,
    emoji: '🇸🇪',
  },
  CH: {
    country: 'Switzerland',
    countryCode: 'CH',
    taxPercent: 8,
    emoji: '🇨🇭',
  },
  SY: {
    country: 'Syria',
    countryCode: 'SY',
    emoji: '🇸🇾',
  },
  TW: {
    country: 'Taiwan',
    countryCode: 'TW',
    emoji: '🇹🇼',
  },
  TJ: {
    country: 'Tajikistan',
    countryCode: 'TJ',
    emoji: '🇹🇯',
  },
  TZ: {
    country: 'Tanzania',
    countryCode: 'TZ',
    emoji: '🇹🇿',
  },
  TH: {
    country: 'Thailand',
    countryCode: 'TH',
    emoji: '🇹🇭',
  },
  TL: {
    country: 'Timor-Leste',
    countryCode: 'TL',
    emoji: '🇹🇱',
  },
  TG: {
    country: 'Togo',
    countryCode: 'TG',
    emoji: '🇹🇬',
  },
  TK: {
    country: 'Tokelau',
    countryCode: 'TK',
    emoji: '🇹🇰',
  },
  TO: {
    country: 'Tonga',
    countryCode: 'TO',
    emoji: '🇹🇴',
  },
  TT: {
    country: 'Trinidad and Tobago',
    countryCode: 'TT',
    emoji: '🇹🇹',
  },
  TN: {
    country: 'Tunisia',
    countryCode: 'TN',
    emoji: '🇹🇳',
  },
  TR: {
    country: 'Turkey',
    countryCode: 'TR',
    emoji: '🇹🇷',
  },
  TM: {
    country: 'Turkmenistan',
    countryCode: 'TM',
    emoji: '🇹🇲',
  },
  TC: {
    country: 'Turks and Caicos Islands',
    countryCode: 'TC',
    emoji: '🇹🇨',
  },
  TV: {
    country: 'Tuvalu',
    countryCode: 'TV',
    emoji: '🇹🇻',
  },
  UG: {
    country: 'Uganda',
    countryCode: 'UG',
    emoji: '🇺🇬',
  },
  UA: {
    country: 'Ukraine',
    countryCode: 'UA',
    taxPercent: 20,
    emoji: '🇺🇦',
  },
  AE: {
    country: 'United Arab Emirates',
    countryCode: 'AE',
    emoji: '🇦🇪',
  },
  GB: {
    country: 'United Kingdom',
    countryCode: 'GB',
    taxPercent: 20,
    emoji: '🇬🇧',
  },
  US: {
    country: 'United States',
    countryCode: 'US',
    emoji: '🇺🇸',
  },
  UM: {
    country: 'United States Minor Outlying Islands',
    countryCode: 'UM',
    emoji: '🇺🇲',
  },
  UY: {
    country: 'Uruguay',
    countryCode: 'UY',
    emoji: '🇺🇾',
  },
  UZ: {
    country: 'Uzbekistan',
    countryCode: 'UZ',
    emoji: '🇺🇿',
  },
  VU: {
    country: 'Vanuatu',
    countryCode: 'VU',
    emoji: '🇻🇺',
  },
  VE: {
    country: 'Venezuela',
    countryCode: 'VE',
    emoji: '🇻🇪',
  },
  VN: {
    country: 'Vietnam',
    countryCode: 'VN',
    emoji: '🇻🇳',
  },
  VG: {
    country: 'British Virgin Islands',
    countryCode: 'VG',
    emoji: '🇻🇬',
  },
  VI: {
    country: 'U.S. Virgin Islands',
    countryCode: 'VI',
    emoji: '🇻🇮',
  },
  WF: {
    country: 'Wallis and Futuna',
    countryCode: 'WF',
    emoji: '🇼🇫',
  },
  EH: {
    country: 'Western Sahara',
    countryCode: 'EH',
    emoji: '🇪🇭',
  },
  YE: {
    country: 'Yemen',
    countryCode: 'YE',
    emoji: '🇾🇪',
  },
  ZM: {
    country: 'Zambia',
    countryCode: 'ZM',
    emoji: '🇿🇲',
  },
  ZW: {
    country: 'Zimbabwe',
    countryCode: 'ZW',
    emoji: '🇿🇼',
  },
}
